### ISSUE TITLE
Fails when used via 'testclient localhost 3000' on connectDelta

### ISSUE THREAD

**Issue by rob42** [SignalK/signalk-js-client#1]
On update-urls branch connect needs 'this' added in connectDelta:

if (host && port) {
    return **this**.connectDelta(options.host + ":" + options.port, options.onData, options.onConnect, options.onDisconnect, options.onError)
  }

**Comment by tkurki** [comment]
Fixed in 7f655a7142135e32f0b926897feea067d88ec14a
