### ISSUE TITLE
Proposal for API

### ISSUE THREAD

**Issue by timmathews** [SignalK/signalk-js-client#22]
# Signal K Client

### Constructor

The constructor should take a single object parameter for configuration, with the following properties:

- `hostname` — Host to connect to, e.g. localhost
- `port` — Override the standard ports of 80/443
- `useTLS` — flag to indicate whether or not the client should use TLS
- `version` — string indicating the version of the Signal K API the client should use, defaults to `v1`
- `onClose` — callback called when the connection is closed, takes two parameters: number and string
- `onError` — callback called when an error occurs, takes a single Error parameter
- `onMessage` — callback called whenever data is received, takes a single Object parameter
- `onOpen` — callback called when the connection is opened, takes no parameters

```javascript
const handleClose = function(code, description) {
  console.warn('Connection was closed with the following code: ' + code + ': ' + description);
};

const handleError = function(error) {
  console.error(error);
};

const handleMessage = function(message) {
  $('.messageElement').innerHTML = JSON.stringify(message, null, 2);
};

handleOpen = function() {
  console.log('Connection established');
};

const skClient = new Client({
  hostname: 'localhost',
  useTLS: true,
  version: 'v1',
  onClose: handleClose,
  onError: handleError,
  onMessage: handleMessage,
  onOpen: handleOpen
});
```

### `Client#connectSync({mdns, primus})`

The `connectSync` method takes an optional object parameter with the following properties:

- `mdns` — if you want to enable mDNS support, pass the mDNS client library here
- `primus` — if you want to use Primus.js instead of raw WebSockets, pass an instance of Primus

and returns a Signal K Connection object with the following signature:

- `hostname` — the host ultimately connected to. This is typically the same as the host passed to the constructor, but might be different if the server has a different WebSockets host configured or if the client received an HTTP redirect or if the host was discovered via mDNS.
- `version` — the version of the Signal K API actually being used. Typically the same as the one requested, but if the server doesn't support the requested version, the next lower version that it does support will be what's used.
- `locale` — the server's locale, used when returning meta data such as unit names and labels.
- `send` — a function which takes a single parameter, either an object or a string to send to the server.
- `disconnect` — a function which takes no parameters and disconnects the WebSockets stream.
- `subscribe` — a function which takes a variable number of string parameters and subscribes to those paths in the default (self) context. Alternatively, it can take a full Signal K subscription object.
- `unsubscribe` — the inverse of the subscribe method.
- `subscribeAll` — a convienence function which subscribes the client to all Signal K paths.
- `unsubscribeAll` — a convienence function which unsubscribes the client from all Signal K paths.

This is a blocking method, prefer the Promise based `connect` instead.

```javascript
import mdns from 'mdns';
import Primus from 'primus';

/* Event handler setup and client instantiation, as above */

const skConnection = skClient.connectSync({mdns: mdns, primus: Primus});
skConnection.subscribe('navigation.*', 'environment.*', 'propulsion.*');

/* or */
skConnection.subscribe({
  "context": "vessels.self",
  "subscribe": [{
    "path": "navigation.*"
  }, {
    "path": "environment.*"
  }, {
    "path": "propulsion.*"
  }]
});

/* or */
skConnection.subscribeAll();
```

Refer the documentation of the [Subscription Protocol](signalk.org/specifiction/master/subscription_protocol.html) for more details.

### `Client#connect({mdns, primus})`

The `connect` method takes the same arguments as the `connectSync` method, but it returns a `Promise` instread of the `skConnection` object.

```javascript
skClient.connect().then(function(skConnection) {
  skConnection.subscribeAll();

  /* or any of the other methods as described above */
});
```

### `Client#get(path)`

A convenience function to get Signal K data from the connected server. This is basically equivalent to usinging the JavaScript Fetch API, with a base path of `<protocol>://<host>:[<port>]/signalk/<version>/api`.

```javascript
skClient.get('/vessels').then(function(result) {
  console.log(result); // urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d
});
```

### `Client#getAvailableVersions()`

Returns an array of version objects describing the Signal K versions that the server supports.

```javascript
skClient.getAvailableVersions().then(function(result) {
  result.forEach(function(version) {
    console.log(version.id + ': ' + version.version); // v1: 1.3.1, v2: 2.0.0.rc1
  };
});
```

A client application may wish to use this information for diagnostic purposes or for finer-grained control over the version of Signal K it is using.

### `Client#getSelf()`

Gets the current full tree from the Signal K server for the `/vessels/self` path.

```javascript
skClient.getSelf().then(function(result) {
  console.log(result);
});
```

This can be useful prior to subscribing to the WebSockets stream to prepopulate an instrument panel, especially for slowly changing data points which would otherwise remain blank until they appeared in the data stream.

### `Client#getSelfMatcher()`

Returns a function which can be used to filter a WebSockets stream for the vessel specified by `self`. Generally, it is better to let the server handle the filtering and only subscribe to to the `self` context. However, this can be useful when displaying data for many vessels (e.g. on a live chart), while maintaining a separate display of local vessel data.

```javascript
skClient.getSelfMatcher().then(function(fnFilter) {
  /* do something with the filter */
});
```

### `Client#getMeta(path, <context>)`

Get metadata for a specific path. Unless a specific context is passed, assumes `self`.

The metadata object contains mostly optional properties. The only required property is `units`. Everything else is optional.

- `shortName` and `longName` — human-friendly display names.
- `units` — one of the Signal K SI abbreviations listed in [Appendix A](http://signalk.org/specification/master/keys/) of the Specification.
- `min` and `max` — min and max expected values for the path.
- `colors` — specifies display colors for different zone types
- `zones` — an array of display zones
  - `lower` and `upper` — start and stop points of zone, the first zone may elide `lower` and last zone `upper`
  - `state` — one of `alarm`, `warn`, `normal`
  - `methods` — an array of methods that the client should use to alert the user if the value enters the zone. Options are `audible` and `visual`
  - `message` — message that should be displayed next to the value

```javascript
skClient.getMeta('electrical.batteries.1.voltage').then(function(meta) {
  console.log(meta);
  /* {
   *   "shortName": "Volts",
   *   "longName": "House Battery Voltage",
   *   "units": "V",
   *   "min": 0,
   *   "max": 16,
   *   "colors": {
   *     "alarm": "#f00",
   *     "warn": "#ff0",
   *     "normal": "#ddd"
   *   },
   *   "zones": [{
   *     "upper": 10,
   *     "state": "alarm",
   *     "methods": ["audible", "visual"],
   *     "message": "Critically low voltage"
   *   }, {
   *     "lower": 10,
   *     "upper": 11.5,
   *     "state": "warn",
   *     "methods": ["visual"],
   *     "message": "Low voltage"
   *   }]
   * }
   */
});
```

## Complete Example

Putting it all together, a simple client application might look something like this:

```javascript
/* Get a reference to the Client class */
/* var Client = require('signalk-client').Client; */
import {Client} from 'signalk-client';

/* Set up some event handlers */
handleClose = function(code, description) {
  console.warn('Connection was closed with the following code: ' + code + ': ' + description);
};

handleError = function(error) {
  console.error(error);
};

handleMessage = function(message) {
  $('.value').innerHTML = message.updates[0].values[0].value;
};

handleOpen = function() {
  console.log('Connection established');
};

/* Create a new Signal K Client with the callbacks, prefer v1 of the API */
const skClient = new Client({
  hostname: 'localhost',
  useTLS: true,
  version: 'v1',
  onClose: handleClose,
  onError: handleError,
  onMessage: handleMessage,
  onOpen: handleOpen
});

/* Open the WebSockets connection, display some system information */
skClient.connect().then(function(skConnection) {
  skConnection.subscribe('navigation.speedOverGround');

  skConnection.getMeta('navigation.speedOverGround').then(function(meta) {
    $('.units').innerHTML = meta.units;
    $('.label').innerHTML = meta.longName;
  });

  $('.systemInfo').innerHTML =
    '<ul><li>Host:' + skConnection.hostname +
    '<li>' + skConnection.version + '</ul>';
});
```

**Comment by tkurki** [comment]
I think there are three somewhat different things here:

### Non connected operations
Mainly discovery. Example use case: _I want to keep an updated list of available, multiple servers_. Discovery is not server specific and inherently async (servers may come and go as equipment is powered up and down).

### Server specific operations
You may want to use a server without a ws connection: query versions and use http api. This should be separate from stuff related to the ws connection, like callbacks and subscriptions.

### Ws connection operations & parameters
Callbacks, subscriptions, selfMatcher. We need to also support the initial ws connection subscription parameter.

Did you do this by hand? I started with something similar quite a while ago, but it never amounted to anything sharable. I did mine with jsdoc from the start: no real code, just a skeleton with annotations. I think it would be fruitful to do it that way in a branch, that way collaboration would be easier.

**Comment by tkurki** [comment]
Are there other discovery libs than `mdns`, or why would you have the user pass in the mdns lib?

**Comment by timmathews** [comment]
I started this in JSDoc in the documentation branch, but then it started to diverge from the actual API, so I switched over to a markdown editor. Converting it back to JSDoc would be pretty simple.

Handling Primus and mdns via dependency injection rather than trying to detect a global Primus object or the existence of a requirable mdns module seems cleaner. Plus, Webpack really doesn't like the conditional `require` (although that can be fixed by marking it external in the config). I think that if the end user wants to use those libraries, they should do so explicitly.

### Non connected operations

I was thinking of the mDNS discovery functions as non-public, had not considered the use case above. I'll add them to the docs. It might make sense to make them static though.

### Server specific operations

The HTTP API get* functions will work independent of the WebSockets stuff, there shouldn't be any issue with calling the constructor without callbacks. In fact, it could be called with no parameters for discovery use cases.

### Ws connection operations & parameters

This supports initial subscription parameters, a few different ways:

```javascript
// Simplest case, context: *, subscribe: *
skConnection.subscribeAll();

// Choosing paths, context: *
skConnection.subscribe('some.path', 'another.path');

// Being very specific
skConnection.subscribe({
  "context": "self",
  "subscribe": [{
    "path": "some.path",
    "period": 1000
  }]
});
```

This could probably also use a `subscribeSelf()` method as well.

I'll see if I can get a new skeleton index.js out to the documentation branch before I go to bed tonight.

**Comment by tkurki** [comment]
Yes, I understand how subscriptions work, but as I understand this can not support the query parameters subscriptions, since the `subscribe` calls happen after connection establishment.

http://signalk.org/specification/master/streaming_api.html#streaming-websocket-api-signalkv1stream

iKommunicate does not support subscription protocol, but supports these query parameters.

Starting with nothing subscribed is a also a very relevant use case - you skip an initial firehose burst that may come right after connection establishment on a busy server.

**Comment by tkurki** [comment]
So if I wanted to use a server's http api I would construct a client without ws callbacks. Would this establish ws connection? 

What if I want to close the ws connection but hold on to the client and maybe establish the ws connection later? If the ws connection errors and closes can I still use the http methods?

Not all of these use cases are very relevant, but I think it would be a good idea to handle the ws connection explicitly and separately instead of implicitly.

A huge hole in the current client is lack of automatic reconnection.

**Comment by tkurki** [comment]
I think we should remove Primus alltogether, it is a relic from earlier times.

**Comment by timmathews** [comment]
All the design is in JSDoc now and I used jsdoc-to-markdown to generate the markdown, which for now, I've appended to the README.md, might redo it to generate docs/README.md instead.

> I think we should remove Primus alltogether, it is a relic from earlier times.

Primus dropped completely, and I moved the mdns param from `connect` to the constructor.

> iKommunicate does not support subscription protocol, but supports these query parameters.

See [connect](https://github.com/SignalK/signalk-js-client/tree/documentation#clientconnectsubscriptiontype). 

> Starting with nothing subscribed is a also a very relevant use case - you skip an initial firehose burst that may come right after connection establishment on a busy server.

This is the default, with no arguments, `connect()` should create a WS connection with `subscribe=none`.

> So if I wanted to use a server's http api I would construct a client without ws callbacks.

Yes

> Would this establish ws connection?

No

> What if I want to close the ws connection but hold on to the client and maybe establish the ws connection later?

Sure. Why would calling `disconnect()` on the `skConnection` object destroy the Client class? Principle of least surprise here.

> If the ws connection errors and closes can I still use the http methods?

Of course, they're not really related at all.

> A huge hole in the current client is lack of automatic reconnection.

I think this is sort of an implementation detail. I don't want to expose reconnect config to the end user, other than maybe a flag to control whether or not auto reconnect should happen. Internally we can do some sort of exponential back-off before eventually giving up.

I think I'll close this issue now in favor of PR #21.
