### ISSUE TITLE
with a websocket the subscription is not functional after the automatic reconnection

### ISSUE THREAD

**Issue by cmotelet** [SignalK/signalk-js-client#44]
### with a websocket the subscription is not functional after the automatic reconnection
Step to reproduice:
- run the code below
- wait for the client to connect and receive delta messages
- restart your signalk server to break the web socket
- the client disconnects, reconnects but not subscribes
- uncomment the line `SignalkClient.unsubscribe();` in connect event or in disconnect event
- run the code below
- wait for the client to connect and receive delta messages
- restart your signalk server to break web socket
- the client disconnects, reconnects and subscribes correctly

I think that  call `unsubscribe()` for cleanning the `subscriptions` object is mandatory in case of disconnection because the first step of connecting to a websocket is done with a `/stream?subscribe=none`.

```
const Client = require('@signalk/client').default;

const SignalkClient = new Client({
  hostname: 'demo.signalk.org',
  port: 80,
  useTLS: false,
  reconnect: true,
  autoConnect: true,
  notifications: false
});
SignalkClient.on('connect', () => {
  console.log('connect event');
//  SignalkClient.unsubscribe();
  SignalkClient.subscribe({context:'vessels.self',subscribe:[{ path:'*'}]});
  SignalkClient.on('delta', (delta) => {console.log('delta event')});
});
SignalkClient.on('error', (err) => {console.log('error event:', err.message)});
SignalkClient.on('disconnect', (data) => {
//  SignalkClient.unsubscribe();
  console.log('disconnect event:', data.type)
});
```

**Comment by fabdrol** [comment]
@cmotelet if I understand you correctly, the problem is:

1. You instantiate a Client and it connects to some server, with a subscription
2. Server dies, websocket goes away
3. Server comes back up, Client reconnects
4. No subscription?

**Comment by fabdrol** [comment]
@cmotelet would you mind testing PR https://github.com/SignalK/signalk-js-client/pull/49 for me? That should fix the issue, I confirmed using a basic unit test case but could use an additional verification. \

Thanks in advance!

**Comment by cmotelet** [comment]
I confirm it's good for me.
The tests with instrumentpanel are also OK.
