### ISSUE TITLE
with websocket the hitMaxRetries event is not raised when value of maxRetries is odd

### ISSUE THREAD

**Issue by cmotelet** [SignalK/signalk-js-client#45]
### with websocket the `hitMaxRetries` event is not raised when value of `maxRetries` is odd
step to reproduce:
- check if port 4000 is not listen on localhost or use another port
- execute the code below and change maxRetries to an odd value

In `connection.js`, `_retries` is incremented twice (in `_onWSError(err)` & `_onWSClose(evt)`) and `this._retries === this.options.maxRetries` is never met with odd value

```
const Client = require('@signalk/client').default;

const SignalkClient = new Client({
  hostname: 'localhost',
  port: 4000,
  useTLS: false,
  reconnect: true,
  autoConnect: true,
  notifications: false,
  maxRetries: 4
});
SignalkClient.on('connect', () => {
  console.log('connect event');
});
SignalkClient.on('error', (err) => {console.log('error event:', err.message)});
SignalkClient.on('disconnect', (data) => {
  console.log('disconnect event:', data.type)
});
SignalkClient.on('hitMaxRetries', () => {console.log('hitMaxRetries event')});
```

**Comment by fabdrol** [comment]
@cmotelet I forgot about this, but this is fixed with #77 . Could you have a look and let me know if it solves the bug for you as well? I implemented your case as a unit test, which passes.
