### ISSUE TITLE
Use WebSocket directly in browser environment

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-js-client#6]
We currently use ws, which supposedly (haven't checked) wraps a browser WebSocket in browser environment.

Upgrading ws to >1.0 makes it incompatible with browser bundling. Right now not bundling is not an option, as the code uses ws and not WebSocket.

Downgrading ws to 0.8 as a stopgap.

https://github.com/websockets/ws/pull/661 for more detail.

**Comment by tkurki** [comment]
Ping @timmathews

**Comment by timmathews** [comment]
Could we replace ws with uWS? https://github.com/alexhultman/uWebSockets
