### ISSUE TITLE
Unsubscribe broken, sends bogus data

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-js-client#72]
```
const Client = require('./').Client


const client = new Client({
    hostname: 'localhost',
    port: 3000,
    useTLS: false
})
client.on('connectionInfo', x => console.log(x))
client.connect().then(() =>
    client.subscribe({
        context: 'vessels.self',
        subscribe: [{ path: 'navigation.position' }]
    }, 'a')
).then(() =>
    client.subscribe({
        context: 'vessels.self',
        subscribe: [{ path: 'navigation.speedOverGround' }]
    }, 'b')
).then(s => {
    s.unsubscribe()
}).catch(e => console.error(e))
```

results in this written to the socket:

`{"context":"vessels.dont_send_me_anything","subscribe":[{"path":"dont_send_me_anything.dont_send_me_anything"}],"format":"delta","policy":"instant"}`

**Comment by fabdrol** [comment]
@tkurki this had to do with something I found in an earlier version, guess I assumed that this was some hack to make server stop sending data. How are we supposed to unsubscribe a subscription from the server without closing the websocket?

**Comment by fabdrol** [comment]
@tkurki please see #74
