### ISSUE TITLE
Simplify subscription mechanisms according to spec

### ISSUE THREAD

**Issue by fabdrol** [SignalK/signalk-js-client#75]
After discussion regarding subscription names, iKommunicate compatibility, and in general the subscription model, the following issues were identified:

- Current subscription mechanism isn't perfect, may need review on a spec level. Out of scope here
- In order to adhere to current mechanism, the implementation in client using "managed" subscriptions identified by unique names is a nice idea but doesn't actually work without changes on server and spec level. 
- This warrants various changes to the client (see below)

Instead of calling `client.subscribe(<opts>, <ident>)`, it makes more sense to instantiate a client with some parameters regarding subscription - since the specification doesn't explicitly support multiple subscriptions on a single WS connection. Example:

```javascript
new Client({
  ... other options
  subscriptionKind: <legacy> | <none> | <self> | <all> | <explicit>, // "legacy" is used for iKommunicate and sorts, where no query params are used
  subscription: { <subscription object> } // relevant when using policy "explicit"
})
```

When the subscription kind is "explicit", the current mechanism is used (subscribe to <none>, then request a subscription over WS).

Additionally, the client should revert to the `legacy` subscriptionKind if a server/gateway responds with Not Implemented (as per spec).

**Comment by tkurki** [comment]
Please rewrite without using the word policy, because it is already used in another meaning in the specification.

I suggest `subscribeQueryParameter` for a new option, so that it maps to the specification text and concepts as well as http terminology.

**Comment by fabdrol** [comment]
I actually prefer configuration names that describe functionality of the software that is being configured (i.e. client) - not names that describe the underlying mechanism. That way, if the mechanism changes, the name still applies to the functionality (despite a different mechanism). 

Also, reading the specification again, we're not really talking about the kind of subscription or such - in "legacy", "all" and "self" modes no subscription takes place. We're really talking about the behaviour of the WS "delta stream". So how about:

```javascript
new Client({
  /* ... other options */
  deltaStreamBehaviour: <legacy> | <self> | <all> | <subscription> | <none>, // "legacy" is used for iKommunicate and sorts, where no query params are used
  subscription: { <subscription object> } // optional, but required when using policy "subscription"
})
```

That describes the _behaviour_ of the delta stream, without being coupled to the mechanism used to influence said behaviour.

**Comment by sbender9** [comment]
Why not just support a `subscriptionQuery` parameter that can be `self`, `all`, `none` or null ?

**Comment by tkurki** [comment]
If you create a new library for something then sure, it makes sense perfect to describe the behaviour exactly the way you want it. 

But in this case imho the main thing is the specification and the client should be easy to use and understand in that context. I think everything in the client should be worded and formatted so that it is as much in line with the specification as possible.

Here you are adding several new concepts, that are not in the specification, but should be somehow mapped to what the spec says:
- _deltaStreamBehavior_ - you need to dpocument what it does, as the streaming chapter in the specification does not use the word _behavior_ at all
- _legacy_ - In computers it means something like _denoting or relating to software or hardware that has been superseded_. I don't see any mechanism here that is superseded by something else - _self_  and _all_ are still totally valid, not in any way legacy imho
- support for only one subscription - the spec explicitly says _You can subscribe to multiple data keys multiple times_, why create an API that looks like it supports only one?

As the client is for both ws and http operations one way to group the stream related options would be 
```
new Client({streamOptions: {.....}, ....})
```

**Comment by fabdrol** [comment]
@tkurki @sbender thanks for your replies.

- I _really_ do not like `subscriptionQuery`, because (a) it will not survive an API change if we resolve some of the issues related to the subscription mechanism; (b) because it's not consistent with the naming strategy for the other option names; and (c) because - unless you know the specification - `query` is actually _less_ descriptive of what that option does. I don't mind documenting this (something I must improve in any case - see another issue).
- `legacy` point taken, I was thinking about iKommunicate being `legacy hardware` in the sense that it's Signal K capabilities have been _superseded_ by newer releases. I'll change it in some way. 
- single subscription: that's something I'm looking into, also because this is currently not backwards compatible. Thing is tho, from the client's perspective there is only one single subscription; sending more 'subscription commands' or 'subscription modifiers' simply changes that single subscription. This is related to our discusion about subscription management and named subscriptions and such. 

If you are _really_ opposed to the use of `behaviour` (as I am to the use of `query`), let's come up with a middle ground. The guide in the specification doesn't specifically name the query thing at all:

> Often you will want to subscribe to a much smaller range of data. Especially for single value displays, it does not make sense to get the entire data stream when only a single value is wanted

A middle ground that is neither `query` nor `behaviour` would be something like `streamSubscriptionRange` or `deltaSubscriptionRange` or whatever.

**Comment by tkurki** [comment]
![image](https://user-images.githubusercontent.com/1049678/79792169-1f600000-8357-11ea-97b7-94c470e368d7.png)

**Comment by tkurki** [comment]
I don't get your point about _surviving an API change_. If we choose to change the API in a non backwards compatible way that will create a new SK version and all bets are basically off - nothing is guaranteed an API change, so why is this a problem?

**Comment by tkurki** [comment]
I am not opposed to _behaviour_, I just think that we should use the same terms in the spec and in the client API.

**Comment by tkurki** [comment]
>Thing is tho, from the client's perspective there is only one single subscription

It seems you are thinking about only unsubscribes.

If I want to subscribe to paths `a.b.c` and `c.d.e` how do I do that with a single subscription? Or to different parts of the tree with different policies. The spec and current server implementation allow these and I think they are legit use cases.

**Comment by fabdrol** [comment]
@tkurki what the client gets is a single stream of data. That stream of data may subscribe to one or more paths, in one or more contexts. As such, sending a `subscribe` command over the web socket is essentially just a _modifier_ for the single data stream that the client has. 

As you pointed out correctly, I am thinking about unsubscribing. If these were multiple, discreet subscriptions a client should be able to unsubscribe from any one of them individually. 

I understand that, on the server, these separate subscriptions may all be, seperate. However, a client will only get one single data stream which includes more or less data based on the subscription commands sent over the WS connection.

**Comment by fabdrol** [comment]
Regarding the `query` thing, I will stick to my guns here. To me, it is most important that a user can understand the client regardless of his/her knowledge of the SK specification. `Query` implies some kind of request, which is completely irrelevant for the abstraction of the data stream. 

If I didn't know the specification, and I read `delta stream behaviour` I would expect the behaviour of the delta stream to be impacted by that option (which it does). If I read `subscriptionQuery`, I'd expect that the option would send some kind of query/question/WHERE modifier to some kind of subscription. Not very clear IMO.

**Comment by tkurki** [comment]
_single stream, one or multiple subscriptions_ sounds like we are talking about the same thing, a bit of misunderstanding on my part.

**Comment by fabdrol** [comment]
I'm working on a new commit to the PR which solves some of the missing bits and points mentioned. What shall I do about the parameter name?

**Comment by fabdrol** [comment]
I updated the PR, resolves most of the issues here. Just the name discussion left 😏. Please see PR
