### ISSUE TITLE
error when Connection.initiateSocket

### ISSUE THREAD

**Issue by flooo11** [SignalK/signalk-js-client#82]
on the file connection.js line 216
`this.socket = new WebSocket(this.wsURI, (this.options.rejectUnauthorized === false) ? {rejectUnauthorized: false} : {})`

According [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications) The second parameter should be a string or an array of strings. So here it is an object.
On my client side, this raize an error :
Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The subprotocol '[object Object]' is invalid.
    at Connection.initiateSocket

**Comment by fabdrol** [comment]
Ah this is a regression due to not checking browser v Node.js. @cmotelet can you address this too in your upcoming PR?

**Comment by cmotelet** [comment]
I'll look at this point tonight, I'm looking for the right way to detect if the code is executed on a browser or in nodejs.
If you have a tip, I'll take it.

**Comment by fabdrol** [comment]
https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js (you could also just use that NPM package, if easier)
