### ISSUE TITLE
Reconnection policy is unusable for real world cases

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-js-client#84]
The current reconnection policy just quickly retries maxRetries times and then gives up all reconnection attempts.

The reconnection policy should back off the retries to something reasonable, in the 5-10 second range by default, and then keep trying.

This would support real world use cases like intermittent connectivity issues, the client app going to sleep and source server reboots and different power up sequences.

See also https://github.com/SignalK/signalk-server-node/issues/1042

**Comment by fabdrol** [comment]
see: https://github.com/SignalK/signalk-js-client/pull/88
