### ISSUE TITLE
Questions and comments about usage

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-js-client#86]
Questions: 

Why does one need to call `connect()` or set `autoConnect: true` to make an http request? Connection always opens a ws connection. What if I just want to make an (authenticated) http request, why the ws?

`client.connect()` Promise apparently resolves even with bad credentials. How do you detect that the login attempt failed because of bad credentials - with autoconnect: true and explicit `connect()` call?

Why is API() a Promise - in what case does it need to be async?

Is there a way to provide the client the auth token from the outside, or is login with username + password the only authentication method?

Comments: 
A server always opens a ws connection to a client, but if there is no read only access you need to login first to receive any data or get any subscriptions processed. However the client sends blindly the initial subscriptions, that will not be handled.

With debug output you always get an error from fetching initial notifications - it is perfectly ok for that path to return 404 under normal circumstances, so should not be logged as error imho.

**Comment by fabdrol** [comment]
> Why does one need to call connect() or set autoConnect: true to make an http request? Connection always opens a ws connection. What if I just want to make an (authenticated) http request, why the ws?

> Why is API() a Promise - in what case does it need to be async?

Both design choices were influenced by an earlier version. There's no technical reason for this and I don't have any particular preference. If you have an issue, or a conflicting use case with it, please raise an issue for that specifically and I'll address it in a future release. I don't think performance is much of an issue here, in any case.

> client.connect() Promise apparently resolves even with bad credentials. How do you detect that the login attempt failed because of bad credentials - with autoconnect: true and explicit connect() call?

I'm not sure if this is an issue or not -- did you test this or is it just something you think? In the latter case, could you provide a case description with expected/actual output?

> Is there a way to provide the client the auth token from the outside, or is login with username + password the only authentication method?

Yep. If you need that, please raise an issue with the feature request with a description of the use case, and I'll implement in a future release.

> A server always opens a ws connection to a client, but if there is no read only access you need to login first to receive any data or get any subscriptions processed. However the client sends blindly the initial subscriptions, that will not be handled

See my first comment, this is a direct result of that choice. I don't see this as much of an issue; if you do, please raise a separate issue and provide a case description. 

> With debug output you always get an error from fetching initial notifications - it is perfectly ok for that path to return 404 under normal circumstances, so should not be logged as error imho.

I do not agree, actually. A 404 is an error (by definition, https://en.wikipedia.org/wiki/HTTP_404) hence I feel it should be logged as such IMO. It doesn't break the client though, as the 404 doesn't break the connection or kill the authentication session, or some other fatal issue.
